### ISSUE TITLE
[Not an issue]Copy request

### ISSUE THREAD

**Issue by Too-Naive** [cnAnonymous/hosts#2]
Hi there,

I am the collaborator of racaljk/hosts. Our hosts project need entrys which them can watch youtube movie where in your project. So I open the issue for request the copy action. Is there have any LICENCE?

Yours truly,
Too-Naive

**Comment by imcaffrey** [comment]
"Our hosts project need entrys which them can watch youtube movie where in your project."
Doubt on this.

**Comment by Too-Naive** [comment]
既然是反代 就算了 @imcaffrey
