### ISSUE TITLE
如果有需要下次更新时加入Google play

### ISSUE THREAD

**Issue by cnAnonymous** [cnAnonymous/hosts#3]
传说中的Google play china版迟迟未到，问问大家用的到play吗？

**Comment by cnAnonymous** [comment]
刚才Windows版谷歌输入法，词库自动更新了，什么情况？三年都没更新过版本了

**Comment by murong1985** [comment]
………翻墙的原因吧

**Comment by murong1985** [comment]
请问大神，最新的文件不支持surge和小火箭了吗？………求支持了吧

**Comment by cnAnonymous** [comment]
surge 到[这里](https://github.com/ifyour/Hosts-for-Surge)更新吧

**Comment by cnAnonymous** [comment]
谁说Youtube的广告短，更你来个长的![doodles](https://lh3.googleusercontent.com/nKoDFTMiuN2mOh8Tz7a5_uTnGZVgK1f4vCQbrU2Ke4j-Kdzm9X7LuVPYw946bWnl2Gx9c6oSP0O-alQguysU15319ZpOInWYft9RsFSeLonESRFx2mqsppw9ycvnzv5EkraYnlO2mFSUMHTKZEVqZYzJSK7Y7nfpHbqrIYxlUzbRxZ0AHIdHcPvq6rKg7aVVyUvg9WY_rLjKcFuQQL-8MS3wGRz35yfnujeDrmhDdElaEj9uI2pZTzsp0m6h-tNonyJCh3CZmHyu6gqsuXpRM2VO9k8jfWmd4LoPGQOcoilsqKSdJa5zqf3WlKbBtJyX8RmGuW0d6qiwHwwZvPeZ1wYR2pVRRL9AwsgX_Opk_Pig6wamBtkd9yAv5yUUiEUYsew2OOSsgc2GDszVLMo_T1BJy5kGCjNRfmRMZYZoiPwsGQddrwtrC3P2eiKgB1pooydJ0QVeu23qp6rwX_MZG5EN8dMZxCw-lIbVovQuI0e_ERzJc1oUQ5_CxDy8xQ_900XzvMOT-HbImoh8l8Ckjtn0QUTgnKZilLdNufTY8BfUBI2Ixm6fv8Pc63WiE9cQOEr1gVpJnhiDIuMw7vNxNGyHygvR2xM=w855-h487-no)

**Comment by murong1985** [comment]
油管的可以跳过吧，我记得五秒就行

**Comment by cnAnonymous** [comment]
好吧，surge还是自己更新吧

**Comment by murong1985** [comment]
😂😂😂这样最好了，你上次给我的网址没有做到三天更新一次 😂😂😂

**Comment by murong1985** [comment]
語法好像有錯誤，第四行和第五行……位置不對吧

**Comment by cnAnonymous** [comment]
刚回来，已修复
