### ISSUE TITLE
能否提供转换成surge的hosts

### ISSUE THREAD

**Issue by sujianchao** [cnAnonymous/hosts#4]
终于找到个能看youtube的hosts，不过我的iphone没有越狱，不能直接替换，只能走surge,能不能提换后提供下载。谢谢

**Comment by cnAnonymous** [comment]
在网上找的样本然后转换的，我没有测试环境你试下[地址](https://raw.githubusercontent.com/cnAnonymous/hosts/master/Surge/hosts)    ，  域名没转换全，可以的话明天全部转换

**Comment by sujianchao** [comment]
你这语法有问题，域名的重定向应该写在hosts条目下，可以用这个自动转[https://github.com/kokororin/hosts2surge](https://github.com/kokororin/hosts2surge)应该没问题。如果需要添加更多的surge功能，可以参考这里去做修改[http://www.abclite.cn/1995.html](http://www.abclite.cn/1995.html)

**Comment by cnAnonymous** [comment]
再试下地址不变，还不行的话晚上回来整

**Comment by sujianchao** [comment]
需要修正rule规则如下:

~[Rule]
~FINAL,DIRECT
修正后一切正常。

**Comment by sujianchao** [comment]
需要修正rule规则如下:
`[Rule]`
`FINAL,DIRECT`
修正后一切正常。

**Comment by cnAnonymous** [comment]
已更新地址不变，fix google应该可以正常使用，文件每次更新，都采用[Google台湾](https://www.google.com.tw/)应急
没有添加屏蔽广告规则，话说以后也不会屏蔽任何商业广告

**Comment by murong1985** [comment]
嗯，上网没问题，广告也不需要屏蔽，就是油管还是只能打开网页无法看……这可能是host的通病了

**Comment by cnAnonymous** [comment]
晚上人多，白天手机应该可以正常观看

**Comment by murong1985** [comment]
谢谢大神！那dns需要锁定不？用114还是8.8呢？或者换成台湾的？

**Comment by cnAnonymous** [comment]
不需要修改任何DNS

**Comment by murong1985** [comment]
好的 谢谢！！
