### ISSUE TITLE
hosts不能用

### ISSUE THREAD

**Issue by 40smile** [cnAnonymous/hosts#5]
今天重装了系统，重装CHORME,然后发现目前所到的hosts全部不可用，，，请教，是hosts的原因，还是系统原因？
另外，同一个hosts，在不同电脑上似乎有不同的上网效果，有的电脑上可用，有的电脑却不可用，何解？

谢谢！

**Comment by cnAnonymous** [comment]
## 以下可能原因
### 1.hosts文件没有成功替换。Windows用notepad++修改文件 Linux需root权限  etc

### 2.文件换行符错误。在Windows下用notepad++按下图转换相应的换行符
![doodles](https://lh3.googleusercontent.com/kED6KkyzxG_0PE7ZIlh1SZdctgoft6EtJppTS25rSZJDdodnpGl7tNUkYKMhxsckojbMmzoq4SQuU3DH1sJdtpn7ePbMcztRwCItHG1QMBgfWAdxQs1aBKVy20OIHa1qhnIYQHnwCJJ3aArRU-cKOWZKSEQFM7zaOQMeUdzXWPMqBRv7wXhL-hUn8qVfrZsdF-GIEJmj470C2wjaRLU5VCXK13-J5WizABzCqem41asKkra07SDgOLvDodlSbM-NLo1zUe1uam3kO93rgzZa3sOBlkeJ4Ly-hw1QwCQjWyhshLoYqjSWQ--yV1ur7L60pPaNmUpAePv2ubVeeGahFDq6CKnxpxuW1yH4N8wEXm2cEwQinbQ6mst4hgX4HAW9fxrcIlDUx42F6uXDe7FNa65eUqdkFt52-Pycvk9N8ZlAODgBzDJt829mwM1fRso4EhrI-pDr86jatxvcTL0XmvM1rv62IVhjW9j4H5oLhKl7OSFa_i6TXD9qkemZTH9vTsRGgTzVIXghwDzyksGtHf08S-pNf_CB1k4gqzdpewgEzSL3n2bL9t8U9sonm1TAFlQD1i1s9LiDUMXqAsrt-16RVn1ASM8=w739-h540-no)
### 3.未开启https。试试打开[m.me](http://m.me)，如果能正常跳转至www.messenger.com，说明hosts功能正常
### 4. Firefox对hosts有时候过敏。更换浏览器

**Comment by 40smile** [comment]
m.me不能正常跳转。我用了“racaljk/hosts”的文件，现在能正常用了。谢谢
