### ISSUE TITLE
换行符有问题吧？

### ISSUE THREAD

**Issue by panpando** [cnAnonymous/hosts#6]
在安卓Drony里拉取后只识别了第一行

**Comment by cnAnonymous** [comment]
你是说用[这个软件](https://play.google.com/store/apps/details?id=org.sandroproxy.drony)？看了下简介不支持hosts吧

**Comment by panpando** [comment]
是啊，用的是dns mapping功能，还挺好用的，导入racaljk的没问题，但他的有些ip连不上，所以想用你的

**Comment by cnAnonymous** [comment]
你还是用能用的吧

**Comment by panpando** [comment]
→_→

**Comment by Hongnanjing** [comment]
😁😁😁
