### ISSUE TITLE
android求救

### ISSUE THREAD

**Issue by tiexo** [cnAnonymous/hosts#7]
魅族手机用的yunos系统，不能root，改不了hosts文件
我看ios不越狱可以用surge，Android怎么办呢？？？

**Comment by Hongnanjing** [comment]
试试刷路由吧 
然后用dnsmasq

**Comment by panpando** [comment]
用drony作本地路由，过几个小时会更新一个新版本

**Comment by tiexo** [comment]
@panpando PAC 脚本地址填哪个？

**Comment by panpando** [comment]
@tiexo 不是pac，是dns mapping
